// src/components/local-time.tsx
import { useEffect, useState } from 'react';

export const LocalTime = () => {
    const [time, setTime] = useState(new Date());

    useEffect(() => {
        const interval = setInterval(() => {
            setTime(new Date());
        }, 1000);
        return () => clearInterval(interval);
    }, []);

    const formattedTime = new Intl.DateTimeFormat('en-GB', {
        hour: '2-digit',
        minute: '2-digit',
        second: '2-digit',
        hour12: false,
        timeZone: 'Europe/Warsaw'
    }).format(time);

    return <span className="">{formattedTime}</span>;
};

// src/components/local-time.svelte
<script>
    import { onMount } from 'svelte';

    let time = $state(new Date());

    onMount(() => {
        const interval = setInterval(() => {
            time = new Date();
        }, 1000);

        return () => clearInterval(interval);
    });

    const formattedTime = $derived(
        new Intl.DateTimeFormat("en-GB", {
            hour: "2-digit",
            minute: "2-digit",
            second: "2-digit",
            hour12: false,
            timeZone: "Europe/Warsaw",
        }).format(time)
    );
</script>

<span>{formattedTime}</span>
